### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../awdlkiller'

### ISSUE THREAD

**Issue by fatdoyy** [jamestut/awdlkiller#2]
Running `installer.py` gave this error on line 102. Any ideas?

`FileNotFoundError: [Errno 2] No such file or directory: '../awdlkiller'`

**Comment by jamestut** [comment]
Oh, please download from the [Release page](https://github.com/jamestut/awdlkiller/releases/tag/v1.1) if you wish to run the `installer.py`.
